Extra annotations in export completed and tested
bihealth/varfish-server pull request #525
Opened 2022-06-02 11:51 UTC by incardon

These are the changes required to export extra_annotation table to xls and tsv.

Tests are included

P.S. Not so sure how test with and without Extra Anno active. So please note

VARFISH_ENABLE_EXTRA_ANNOS = env.bool("VARFISH_ENABLE_EXTRA_ANNOS", True)

That would change the default setting.

Otherwise the code is pretty straighforward there is 

RowWithExtraAnno that wrap the result table in order to make the exporters working with the additional columns.

The additional columns are added in the base exported is extra anno is active and based on the fields in the database

2022-06-09 17:20 UTC, holtgrewe commented
Hi @incardon - thank you for the patch. It appears to me that the link to the original issue that was written before the development started is missing. Could you adjust this so it fits the process / structure.

2022-06-09 20:01 UTC, incardon commented
should be done

2022-06-10 06:50 UTC, holtgrewe commented
@incardon thank you. It looks like we are missing the [Design](https://varfish-server.readthedocs.io/en/latest/developer_templates.html#design) for the patch that precedes coding in the process.

2022-06-13 07:41 UTC, holtgrewe commented
> P.S. Not so sure how test with and without Extra Anno active. So please note

Good point. See https://github.com/bihealth/varfish-server/issues/495#issuecomment-1153582838

2022-06-24 10:47 UTC, holtgrewe requested changes
LGTM but please squash both commits

2022-06-24 10:48 UTC, holtgrewe commented
Also, please rebase on latest `main` and add note to `HISTORY.rst`.

2022-06-24 11:11 UTC, holtgrewe commented
Once the squashed and rebased changes pass CI, please make a backport of this patch to the anthenea.

We usually do this by checking out the `anthenea` branch and then cherry-picking the relevant patches and pushing them to a new branch that has the same name as the original one for `main` and adding a `-backport` suffix. You will find many examples in the currently open PRs.

2022-06-24 13:18 UTC, incardon commented
Thanks in this moment I cannot guarantee, when I will have time to do it.

2022-06-27 21:33 UTC, incardon commented
should be done

2022-06-28 06:18 UTC, holtgrewe approved these changes

2022-06-28 06:18 UTC, holtgrewe commented
Thanks, merging.

2022-06-28 06:18 UTC, merged